name: azstore
description: Dart package to access azure storage options with easy to use functions. This package handles formatting of HTTPS requests to access azure REST APIs.
version: 1.0.0
homepage: https://github.com/Algure/azstore
repository: https://github.com/Algure/azstore.git

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto: ^3.0.5
  http: ^1.2.2
  xml: ^6.5.0
  universal_io: ^2.2.2

dev_dependencies:
  lints: ^4.0.0
  mockito: ^5.4.4
  test: ^1.21.4